

#ifndef MAC_MOUSECODE_H
# define MAC_MOUSECODE_H

//== MOUSE CODE ==//
#define MOUSE_LEFT_BUTTON 1
#define MOUSE_RIGHT_BUTTON 2
#define MOUSE_SCROLL_BUTTON 3
#define MOUSE_SCROLL_UP 4
#define MOUSE_SCROLL_DOWN 5 

#endif